config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    # Django admin urls
    path('admin/', admin.site.urls),
    
    # Allauth urls
    path('accounts/', include('allauth.urls')),
    
    # Product app urls
    path('', include('product.urls', namespace='product')),
    
    # Ckeditor5 urls
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),

]

# serve static and media files from development server
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Django rosetta urls
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path("", views.product_list_view, name="product_list"),
    path("product/<int:product_id>/detail/", views.product_detail_view, name="product_detail"),
    path("search/", views.search_view, name="search"),
]

product/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
# from ckeditor_uploader.fields import RichTextUploadingField
from django_ckeditor_5.fields import CKEditor5Field
from django.urls import reverse



class ProductManager(models.Manager):
    def active_products(self):
        return self.prefetch_related("product_images").filter(is_active=True).order_by('id')


class Product(models.Model):
    CHOICES_STATUS = [
        ("none", _("none")),
        ("size", _("size")),
        ("color", _("color")),
        ("both", _("both")),
    ]
    
    name = models.CharField(_("name"), max_length=255, unique=True)

    slug = models.SlugField(_("slug"), max_length=255, unique=True)
    
    content = CKEditor5Field(_("content"), config_name='extends')
    
    image = models.ImageField(_("image"), upload_to="images/")
    
    colors = models.ManyToManyField('Color', related_name='products', verbose_name=_('colors'), blank=True, null=True)
    
    sizes = models.ManyToManyField('Size', related_name='products', verbose_name=_('sizes'), blank=True, null=True)
    
    datetime_created = models.DateTimeField(_("datetime_created"), auto_now_add=True)
    
    datetime_updated = models.DateTimeField(_("datetime_updated"), auto_now=True)
    
    status = models.CharField(_("status"), max_length=10, choices=CHOICES_STATUS)
    
    is_active = models.BooleanField(_("is_active"), default=True)

    objects = ProductManager()


    def __str__(self):
        return self.name
    
    class Meta:
        db_table = ''
        managed = True
        verbose_name = _('product')
        verbose_name_plural = _('products')

    def get_absolute_url(self):
        return reverse("product:product_detail", kwargs={"product_id": self.id})
    
    def colors_to_str(self):
        return " - ".join([color.name for color in self.colors.all()])
    colors_to_str.short_description = _('colors')
    
    def sizes_to_str(self):
        return " - ".join([size.name for size in self.sizes.all()])
    sizes_to_str.short_description = _('sizes')




class ProductImages(models.Model):
    product = models.ForeignKey(Product, verbose_name=_("product"), on_delete=models.CASCADE, related_name="product_images")

    number = models.PositiveIntegerField(_("number"),)

    image = models.ImageField(_("image"), upload_to="images/")

    class Meta:
        db_table = ''
        managed = True
        verbose_name = _('productimage')
        verbose_name_plural = _('productimages')


class Color(models.Model):
    name = models.CharField(_('name'), max_length=255, unique=True)

    def __str__(self):
        return self.name
    
    class Meta:
        db_table = ''
        managed = True
        verbose_name = _('color')
        verbose_name_plural = _('colors')


class Size(models.Model):
    name = models.CharField(_('name'), max_length=255, unique=True)

    def __str__(self):
        return self.name
    
    class Meta:
        db_table = ''
        managed = True
        verbose_name = _('size')
        verbose_name_plural = _('sizes')


class Variant(models.Model):
    product = models.ForeignKey(Product, verbose_name=_("product"), related_name="product_variants", on_delete=models.CASCADE)

    color = models.ForeignKey(Color, verbose_name=_("color"), related_name="color_variants", on_delete=models.CASCADE, blank=True, null=True)

    size = models.ForeignKey(Size, verbose_name=_("size"), related_name="size_variants", on_delete=models.CASCADE, blank=True, null=True)

    price = models.PositiveIntegerField(_("price"))

    discount = models.PositiveIntegerField(_("discount"), blank=True, null=True)

    total_price = models.PositiveIntegerField(_("total_price"))

    inventory = models.PositiveIntegerField(_("inventory"), default=0)


    def __str__(self):
        return self.product.name

    def __unicode__(self):
        return 'product id: {}'.format(self.product.id)
    
    class Meta:
        db_table = ''
        managed = True
        verbose_name = _('variant')
        verbose_name_plural = _('variants')

    # def get_absolute_url(self):
    #     return reverse("product:product_detail", kwargs={"variant_id": self.id})
    
    @property
    def total_price(self):
        """
            We use this method to calculate the total price if is there any discount for variant.
            and we use this decorator to show this method as attribute for variant and django will fill is in database automatically.
        """
        if not self.discount :
            return self.price
        else:
            discount_price = (self.discount * self.price) / 100
            return int(self.price - discount_price)
        return self.total_price 

product/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(max_length=250)
    

product/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.db.models import Q

from .models import Product, ProductImages, Variant
from .forms import SearchForm


@require_POST
def search_view(request):
    search = SearchForm(request.POST)
    if search.is_valid():
        data = search.cleaned_data['search']
        if data.isdigit():
            products = Product.objects.filter(Q(price__exact=data) | Q(discount__exact=data))
        else:
            products = Product.objects.filter(Q(name__icontains=data) | Q(content__icontains=data))

        return render(request, 'product/product_list.html', {"products": products})


def product_list_view(request):
    products = Product.objects.active_products
    
    context = {
        'products' : products
    }

    return render(request, 'product/product_list.html', context)


def product_detail_view(request, product_id):
    # product_queryset = Product.objects.prefetch_related("comments").select_related("category").filter(is_active=True)
    
    product = get_object_or_404(Product, id=product_id)
    
    product_images = ProductImages.objects.filter(product__id = product_id)
    
    if request.method == "POST":
        product_variants = Variant.objects.filter(product__id = product_id)
        
        user_select = request.POST.get("select")
        
        variant_select = Variant.objects.select_related("size").get(id= user_select)
        
        variant_sizes = Variant.objects.select_related("size").filter(product__id=product_id).distinct('size__id')
        
        variant_colors = Variant.objects.select_related("color").filter(product__id= product.id, size__id= variant_select.size.id)
        
    else:
        product_variants = Variant.objects.filter(product__id = product_id)
        
        variant_select = Variant.objects.get(id= product_variants[0].id)
        
        variant_sizes = Variant.objects.select_related("size").filter(product__id=product_id).distinct('size__id')

        variant_colors = Variant.objects.select_related("color").filter(product__id= product.id, size__id= product_variants[0].size_id)


    context = {
        "product": product,
        "product_images": product_images,
        "product_variants": product_variants,
        "variant_select": variant_select,
        "variant_sizes": variant_sizes,
        "variant_colors": variant_colors,
    }
    
    return render(request, 'product/product_detail.html', context)

product/templates/product/product_detail.html
{% extends '_base.html' %}

<!-- Django template tags -->
{% load static %}
{% load i18n %}

<!-- Third party template tags -->
{% load thumbnail %}


{% block title %}

    {% trans "Product Detail" %}

{% endblock %}

{% block body %}


	<div class="breadcumb_area">
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="bread_box">
						<ul class="breadcumb">
							<li><a href="{% url "product:product_list" %}">{% trans "home"%} <span>|</span></a></li>
							<li><a href="#">{{ product.name }}<span>|</span></a></li>
							<li><a href="#">{% trans "details"%}<span>|</span></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<section class="gray_tshirt_area">
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="gray_tshirt">
					<div class="row">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<div class="single_product_image_tab">
							<div role="tabpanel">

								<!-- Nav tabs -->
								<ul class="nav nav-tabs product_detail_zoom_tab" role="tablist" style="left: 0px; top: 0px;">
									<li role="presentation" class="active" ><a href="#{{ product.id }}" aria-controls="{{ product.id }}" role="tab" data-toggle="tab">
										<div class="small_img">
											{% comment %} {% thumbnail product.image "82x95" crop="center" as im %} {% endcomment %}
											<img src="{{ product.image.url }}" width="82px" height="95px" alt=""/>
											{% comment %} {% endthumbnail %} {% endcomment %}
										</div>
									</a></li>
									{% for product_image in product_images %}
										<li role="presentation" ><a href="#{{ product_image.id }}" aria-controls="{{ product_image.id }}" role="tab" data-toggle="tab">
											<div class="small_img">
												{% comment %} {% thumbnail product_image.image "82x95" crop="center" as im %} {% endcomment %}
												<img src="{{ product_image.image.url }}" width="82px" height="95px" alt=""/>
												{% comment %} {% endthumbnail %} {% endcomment %}
											</div>
										</a></li>
									{% endfor %}
								</ul>

								<!-- Tab panes -->
								<div class="tab-content">
									<div role="tabpanel" class="tab-pane active " id ="{{ product.id }}" >
										<div class="single_p_image">
										{% comment %} {% thumbnail product.image "546x936" as big %}
										{% thumbnail product.image "346x651" crop="left" as small %} {% endcomment %}
										{% comment %} <a href="{{ big.url}}" title="look ma!"><img src="{{ small.url }}"></a> {% endcomment %}
											<a href="{{ product.image.url}}" data-lightbox="image-1" data-title="My caption"><img src="{% static "images/product-plus.png"%}" alt="" /></a>
											<img id="zoom_00" src="{{ product.image.url }}" data-zoom-image="{{ product.image.url}}" width="346px" height="651px" alt=""/>
											{% comment %} {% endthumbnail %}
											{% endthumbnail %} {% endcomment %}
										</div>
									</div>
									{% for product_image in product_images %}
										<div role="tabpanel" class="tab-pane " id ="{{ product_image.id }}" >
											<div class="single_p_image">
											{% comment %} {% thumbnail product_image.image "546x936" as big %}
											{% thumbnail product_image.image "346x651" crop="left" as small %} {% endcomment %}
											{% comment %} <a href="{{ big.url}}" title="look ma!"><img src="{{ small.url }}"></a> {% endcomment %}
												<a href="{{ product_image.image.url}}" data-lightbox="image-1" data-title="My caption"><img src="{% static "images/product-plus.png"%}" alt="" /></a>
												<img id="zoom_0{{ forloop.counter }}" src="{{ product_image.image.url }}" data-zoom-image="{{ product_image.image.url}}" width="346px" height="651px" alt=""/>
												{% comment %} {% endthumbnail %}
												{% endthumbnail %} {% endcomment %}
											</div>
										</div>
									{% endfor %}
								</div>	
							</div>
						</div>
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
					
						<div class="product_detail_heading">
							<div class="detail_heading_left">
								<h3>{{ product.name }}</h3>
							</div>
							<div class="detail_heading_right">
								{% comment %} 
									<ul id="detail_star">
										<li><a class="fa fa-star-o red" href=""></a></li>
										<li><a class="fa fa-star-o red" href=""></a></li>
										<li><a class="fa fa-star-o red" href=""></a></li>
										<li><a class="fa fa-star-o" href=""></a></li>
										<li><a class="fa fa-star-o" href=""></a></li>
									</ul>
									<p>(5 Review)</p> 
								{% endcomment %}
							</div>
						</div>
						
						<div class="panel-group product_accordion" id="home-accordion-single" role="tablist" aria-multiselectable="true">
						<div class="panel panel-default product_default">
							<div class="panel-heading product_accordion_heading" role="tablist" id="headingOneP">
							<h4 class="panel-title product_accordion_head">
								<a data-toggle="collapse" data-parent="#home-accordion-single" href="#collapseOneP" aria-expanded="false" aria-controls="collapseOneP">
									{% trans "Description" %}
								<span class="floatright"><i class="fa fa-plus"></i></span>
								</a>
							</h4>
							</div>
							<div id="collapseOneP" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOneP">
								<div class="panel-body product_ac_body">
								<p>
									{{ product.content|safe }}
								</p>
							</div>
							</div>
						</div>
						<div class="panel panel-default product_default">
							<div class="panel-heading product_accordion_heading" role="tab" id="headingThreeP">
								<h4 class="panel-title product_accordion_head">
							<a class="collapsed" data-toggle="collapse" data-parent="#home-accordion-single" href="#collapseThreeP" aria-expanded="false" aria-controls="collapseThreeP">
								{% trans "size & fit" %}
								<span class="floatright"><i class="fa fa-plus"></i></span>
							</a>
							</h4>
							</div>
							<div id="collapseThreeP" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThreeP">
								<div class="panel-body product_accordion_head">
								<div class="single_color">
									<div class="color_heading">
										<h5>{% trans "Select size"%}</h5>
									</div>
									<form method="post" action=".">
										{% csrf_token %}
										<div class="color_detail">
											<div class="color_size_detail">
												{% for variant in variant_sizes %}
													{% comment %} {% if size in variant %} {% endcomment %}
														<ul id="color_size">
															<button name="select" type="radio" value="{{ variant.size_id }}"
																{% if variant_select.size_id == variant.size_id %} checked {% endif %}
																onchange="this.form.submit();"
															>
																<li><a href="">{{ variant.size.name }}</a></li>
															</button>
														</ul>
													{% comment %} {% endif %} {% endcomment %}
												{% endfor %}	
											</div>
										</div>
									</form>
								</div>
								<div class="single_color sp_single_col">
									<div class="color_heading">
										<h5>{% trans "Colors"%}</h5>
									</div>
									<form method="post" action=".">
										{% csrf_token %}
										<div class="color_detail">
											<div class="panel-body colors_cat">
												{% for variant in variant_colors %}
													{% comment %} {% if color in variant %} {% endcomment %}
														<ul id="cat_color">
															<input name="select" type="radio" value="{{ variant.id }}"
																{% if variant_select.id == variant.id %} checked {% endif %}
																onchange="this.form.submit();"
															>
															{% comment %} <li><a class="col-7" href="">{{ variant.color.name}}</a></li> {% endcomment %}
															<li><a href="">{{ variant.color.name}}</a></li>
														</ul>
													{% comment %} {% endif %} {% endcomment %}
												{% endfor %}
											</div>
										</div>
									</form>
								</div>
								<div class="single_color">
									<div class="color_heading">
										<h5>{% trans "Price"%}</h5>
									</div>
									<div class="color_detail">
										{% if variant_select.discount %}
											<div class="old_price_gray"><p> {% trans "$" %}{{ variant_select.total_price }} </p></div>
											<div class="new_price_gray"><del> {% trans "$" %}{{ variant_select.price }} </del></div>
										{% else %}
											<div class="old_price_gray"><p> {% trans "$" %}{{ variant_select.price }} </p></div>
										{% endif %}
									</div>
								</div>
								<div class="single_color">
									<div class="color_heading">
										<h5>{% trans "Quantity"%}</h5>
									</div>
									<div class="color_detail">
										<div class="size_down">
											<input type="number" size="4" class="input-text qty text" title="Qty" value="1" name="quantity[113]" max="119" min="0" step="1">
										</div>
										<div class="size_cart">
											<a href="">{% trans "Add to cart"%}</a>
										</div>
										<div class="size_heart">
											<a href=""><img src="{% static "images/Product-Details-heart.png" %}" alt="" /></a>
										</div>
										<div class="size_heart">
											<a href=""><img src="{% static "images/Product-Details-arrow.png" %}" alt="" /></a>
										</div>
									</div>
								</div>
								
								</div>
							</div>
						</div>
					</div>
						
					</div>
					</div>
				</div>
				</div>
			</div>
		</div>
	</section>
	
    <script>
        $(function() {
        $( "#slider-range" ).slider({
            range: true,
            min: 150,
            max: 1500,
            values: [ 520, 1100 ],
            slide: function( event, ui ) {
            $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
            }
        });
        $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
            " - $" + $( "#slider-range" ).slider( "values", 1 ) );
        });
    </script>

{% endblock %}

product/templates/product/product_list.html
{% extends "_base.html" %}

<!-- Django Template Filter -->
{% load static %}
{% load i18n %}

{% block title %}

    {% trans 'product list' %}

{% endblock %}

{% block body %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        <!-- /.row -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                    <h1 class="card-title" style="font-size: 4.1rem;">{% trans "Product List" %} </h1>
                        <div class="card-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <form method="post" action="{% url 'product:search' %}">
                                    {% csrf_token %}
                                    <input type="text" name="search" class="form-control float-right" placeholder="{% trans "Search" %}">
                                    
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>{% trans "ID" %}</th>
                                    <th>{% trans "image" %}</th>
                                    <th>{% trans "NAME" %}</th>
                                    <th>{% trans "COLORS" %}</th>
                                    <th>{% trans "SIZES" %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product in products %}
                                    <tr>
                                        <td>{{ product.id }}</td>
                                        <td style= 'max-width: 20.666667%;'>
                                            <div class="filtr-item col-sm-2" style= 'max-width: 16%;' data-category="1" data-sort="white sample">
                                                <a href="{{ product.image.url }}" data-toggle="lightbox" data-title="sample 1 - white">
                                                    <img src="{{ product.image.url }}" style= 'max-width: 160px;' class="img-fluid mb-2" alt="white sample"/>
                                                </a>
                                            </div>
                                        </td>
                                        <td>    
                                            <li class="nav-item d-none d-sm-inline-block">
                                                <a href="{{ product.get_absolute_url }}" class="nav-link">{{ product.name }}</a>
                                            </li>
                                        </td>
                                        <td>{{ product.colors_to_str }}</td>
                                        <td>{{ product.sizes_to_str }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            <!-- /.card -->
            </div>
        </div>
        <!-- /.row -->

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

{% endblock %}